# Generated by Django 2.1.1 on 2022-09-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HATCH', 'Hatch'), ('SEDAN', 'Sedan'), ('CONVERSIVEL', 'Conversivel')], max_length=15)),
                ('cor', models.CharField(choices=[('AMARELO', 'Amarelo'), ('AZUL', 'Azul'), ('CINZENTO', 'Cinzento')], max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'verbose_name_plural': 'Locações',
            },
        ),
    ]
