# Generated by Django 2.1.1 on 2022-09-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='cor',
            field=models.CharField(choices=[('AMARELO', 'Amarelo'), ('AZUL', 'Azul'), ('CINZA', 'Cinza')], max_length=15),
        ),
    ]
